### PR TITLE
Order history

### PR DESCRIPTION
**Pull request by chawes13**
connects to #4 
connects to #66 
connects to #67

### CODE REVIEW

**Comment by chawes13** [comment]
Requested job isn't supposed to do anything yet. I plan on hooking it up to the logic (or similar) that you wrote today. Will select seed data for the beta testing such that this scenario doesn't occur. Looking into points 1 and 3 now.

**Comment by chawes13** [comment]
1st issue is fixed by a PR in Web on order-history

**Comment by chawes13** [comment]
Date formatting fixed

**Comment by drevets** [comment]
look good! merging

**Pull request merged**
